<<<<<<< HEAD

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# example netlify.toml
[build]
  command = "npm run build"
  functions = "lambda" #  netlify-lambda reads this
  publish = "build"
=======
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
>>>>>>> 27df4244542756bfb7e5c0ed54c2084f96e6f0c9
