[[redirects]]
  from = "/api"
  to = "https://zeelcodder.tech/.netlify/functions"
  status = 200


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# example netlify.toml
[build]
  command = "npm run build"
  functions = "lambda" #  netlify-lambda reads this
  publish = "build"
